site_name: DronePG
theme: readthedocs
repo_url: https://github.com/dronepg/docs/
markdown_extensions:
  - admonition
  - toc:
        permalink: "#"
        baselevel: 2
nav:
  - 'levees.md'
  - 'Teoria':
    - 'dem/nmt.md'
    - 'dem/lidar.md'
    - 'dem/photogrammetry.md'
    - 'dem/comparasion.md'
    - 'dem/yellowscan.md'
    - 'dem/applanix.md'      
  - SAFEDAM:
    - Projekt: 'safedam/safedam.md'
    - 'safedam/neo3.md'
    - 'safedam/zawisak.md'
  - 'questions.md'
